# Generated by Django 5.2.12 on 2026-03-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['discord_id', '-attempted_at'], name='team_linkra_discord_517b86_idx')],
            },
        ),
        migrations.CreateModel(
            name='LinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('discord_id', models.BigIntegerField()),
                ('discord_username', models.CharField(max_length=255)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['token', 'used', 'expires_at'], name='team_linkto_token_e1d8eb_idx')],
            },
        ),
    ]
