"""Views for ECS 198F Discord authentication."""

import logging
from typing import cast
from urllib.parse import quote

from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render

from core.services.linking import LinkResult, validate_link_token
from team.models import LinkToken

from .auth_utils import get_authentik_groups, get_authentik_id

logger = logging.getLogger(__name__)

# Expiry used by the 198F token-based auth flow
TOKEN_EXPIRY_MINUTES = 15

# Authentik group required to receive the ecs198f-student Discord role
ECS198F_REQUIRED_GROUP = "198F-student"


def health_check(request: HttpRequest) -> HttpResponse:
    """Simple health-check endpoint for monitoring."""
    return HttpResponse("OK", content_type="text/plain")


def auth_198f_initiate(request: HttpRequest) -> HttpResponse:
    """Initiate the ECS 198F OAuth linking flow.

    Validates the one-time token generated by the Discord button and
    redirects the user to Authentik for authentication.
    """
    token = request.GET.get("token")

    if not token:
        return HttpResponse("Missing token parameter", status=400)

    try:
        link_token = LinkToken.objects.get(token=token, used=False)
    except LinkToken.DoesNotExist:
        return render(
            request,
            "link_error.html",
            {
                "error": "Invalid or expired token",
                "message": "This link has expired or is invalid. Please click the Authenticate button again.",
            },
        )

    if link_token.is_expired():
        return render(
            request,
            "link_error.html",
            {
                "error": "Token expired",
                "message": (
                    f"This link has expired ({TOKEN_EXPIRY_MINUTES}-minute limit). "
                    "Please click the Authenticate button in Discord again."
                ),
            },
        )

    # Store token in session for CSRF protection
    request.session["pending_198f_token"] = link_token.token

    next_url = quote(f"/auth/198f-callback?token={link_token.token}", safe="")
    return redirect(f"/auth/login/?next={next_url}")


def auth_198f_callback(request: HttpRequest) -> HttpResponse:
    """Handle the OAuth callback for the ECS 198F auth flow.

    Verifies the user belongs to the ``198F-student`` Authentik group and,
    if so, queues a Discord task to assign the ``ecs198f-student`` role.
    """
    from core.models import DiscordTask

    list(messages.get_messages(request))  # discard any stray messages

    user = cast(User, request.user)
    try:
        authentik_username = user.username
        groups = get_authentik_groups(user)
        authentik_user_id = get_authentik_id(user)
    except Exception as e:
        logger.error(f"auth_198f_callback: Error getting Authentik data: {e}", exc_info=True)
        raise

    if not authentik_user_id:
        return render(
            request,
            "link_error.html",
            {
                "error": "Authentication error",
                "message": "Could not retrieve your Authentik account information.",
            },
        )

    # Validate token from URL + session
    url_token = request.GET.get("token")
    session_token = request.session.get("pending_198f_token")
    token_result = validate_link_token(url_token, session_token, authentik_username)
    if isinstance(token_result, LinkResult):
        return render(request, cast(str, token_result.error_template), token_result.error_context)
    link_token = token_result

    discord_id = link_token.discord_id
    discord_username = link_token.discord_username

    # Verify the user is in the required Authentik group
    if ECS198F_REQUIRED_GROUP not in groups:
        logger.info(
            f"auth_198f_callback: {authentik_username} does not have group '{ECS198F_REQUIRED_GROUP}' "
            f"(groups: {groups})"
        )
        return render(
            request,
            "link_error.html",
            {
                "error": "Access denied",
                "message": (
                    f"Your account does not have the required '{ECS198F_REQUIRED_GROUP}' group in Authentik. "
                    "Please contact your instructor if you believe this is an error."
                ),
            },
        )

    # Mark token as used and assign the Discord role
    link_token.used = True
    link_token.save(update_fields=["used"])

    DiscordTask.create_assign_group_roles(discord_id, groups)
    logger.info(
        f"auth_198f_callback: queued assign_group_roles for {discord_username} ({discord_id}); "
        f"groups={groups}"
    )

    # Clean up session
    request.session.pop("pending_198f_token", None)

    return render(
        request,
        "auth_198f_success.html",
        {
            "discord_username": discord_username,
            "authentik_username": authentik_username,
        },
    )
